Added Helm .Files
norwoodj/helm-docs pull request #139
Opened 2022-04-26 14:06 UTC by terrycain

Related to #107 its an initial go at adding a basic .Files value into the template context.
Is near identical to the actual Helm implementation albeit a simplified one.

For this I've added the `github.com/gobwas/glob` dependency which helm also pulls in.

2022-05-10 10:04 UTC, norwoodj requested changes

2022-05-10 10:04 UTC, norwoodj commented on pkg/document/files.go
> +		data, err := ioutil.ReadFile(path)
I would prefer we lazily read the contents of the files. As it is, you're loading the content of all files in all chart directories into memory.

Instead, I'd prefer you do something like:
```
type fileContent{
    path string
    data []byte
}

func (f *fileContent) getData() {
    if f.data == nil {
        f.data = ioutil.ReadFile(f.path)
    }
    
    return f.data
}
```

Then replace all direct references to f.data with f.getData().

    

    
    

type files map[string][]byte

2022-05-10 10:04 UTC, norwoodj commented on pkg/document/files.go
> +	if err != nil {
If the pattern fails, why recursively select all files? I think instead you should return an empty `files` and log a warning.

2022-05-10 10:04 UTC, norwoodj commented on pkg/document/files.go
> +	if err != nil {
If the pattern fails, why recursively select all files? I think instead you should return an empty list and log a warning.

2022-05-11 18:49 UTC, terrycain commented on pkg/document/files.go
> +		data, err := ioutil.ReadFile(path)
Good idea, done :smile:

2022-05-11 18:50 UTC, terrycain commented on pkg/document/files.go
> +	if err != nil {
Logged out an error and returned an empty collection

2022-05-27 13:49 UTC, terrycain commented
@norwoodj are these changes sufficient?

2022-06-29 09:56 UTC, merged